spring:
  application:
    name: quickbite


  datasource:
    url: jdbc:mysql://localhost:3306/quickbite
    username: root
    password: Waheguru&7788
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
